name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Auto Grading
      id: auto-grading
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Auto Grading
        setup-command: ''
        command: "./runtest.sh"
        timeout: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        AUTO-GRADING_RESULTS: "${{steps.auto-grading.outputs.result}}"
      with:
        runners: auto-grading
